// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/teitei-tk/goodbyte-twitter-history/cli"
)

// Injectors from wire.go:

func InitializeApp(flags *cli.CliFlags) *App {
	appConf := &AppConf{
		Input: flags,
	}
	app := NewApp(appConf)
	return app
}

// wire.go:

func appConfig(flags *cli.CliFlags) *AppConf {
	return &AppConf{
		Input: flags,
	}
}
