// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/teitei-tk/go-tweetdel/app"
	"github.com/teitei-tk/go-tweetdel/cli"
)

// Injectors from wire.go:

func InitializeApp(flags *cli.CliFlags) *app.App {
	appConf := &app.AppConf{
		Input: flags,
	}
	appApp := app.NewApp(appConf)
	return appApp
}

// wire.go:

func appConfig(flags *cli.CliFlags) *app.AppConf {
	return &app.AppConf{
		Input: flags,
	}
}
